import Link from "next/link";
import { Button, Card, ThemeToggle } from "@openseat/design-system";

export default function Home() {
  return <main style={{ minHeight: "100vh", background: "var(--canvas)", color: "var(--ink)" }}>
    <header className="os-nav"><span className="h3 os-nav-brand">OpenSeat</span><nav className="os-nav-items" aria-label="Primary navigation"><a className="label os-nav-item" href="#how-it-works">How it works</a><a className="label os-nav-item" href="/style-guide">Design system</a></nav><div className="os-nav-right"><ThemeToggle /><Link href="/marketplace/login"><Button variant="secondary" size="sm">Sign in</Button></Link></div></header>
    <section style={{ maxWidth: 1180, margin: "0 auto", padding: "clamp(64px, 12vw, 144px) 24px 96px", display: "grid", gridTemplateColumns: "1.2fr .8fr", gap: 64, alignItems: "center" }}><div><span className="label text-primary">THE WORK MARKETPLACE</span><h1 className="display" style={{ fontSize: "clamp(48px, 7vw, 88px)", maxWidth: 760, margin: "16px 0" }}>Find the right people for meaningful work.</h1><p className="body-lg text-ink-muted" style={{ maxWidth: 620 }}>OpenSeat connects clients with focused candidates through clear briefs, thoughtful bids, and conversations that lead to better contracts.</p><div style={{ display: "flex", flexWrap: "wrap", gap: 12, marginTop: 32 }}><Link href="/marketplace/jobs"><Button variant="primary" size="lg">Explore marketplace</Button></Link><Link href="/marketplace/register"><Button variant="secondary" size="lg">Create an account</Button></Link></div></div><Card title="A calmer way to work" meta="One shared workflow for candidates and clients" raised><div style={{ display: "grid", gap: 16, marginTop: 20 }}><div><span className="label text-primary">01</span><p className="body-strong">Discover</p><p className="body-sm text-ink-muted">Browse job rooms with transparent scope, budget, and expectations.</p></div><div><span className="label text-primary">02</span><p className="body-strong">Discuss</p><p className="body-sm text-ink-muted">Ask questions and refine the work before anyone commits.</p></div><div><span className="label text-primary">03</span><p className="body-strong">Deliver</p><p className="body-sm text-ink-muted">Move from an approved bid to milestones and active work.</p></div></div></Card></section>
    <section id="how-it-works" style={{ maxWidth: 1180, margin: "0 auto", padding: "0 24px 96px", display: "grid", gridTemplateColumns: "1fr 1fr", gap: 24 }}><Card title="For candidates" meta="Bid with confidence"><p className="body text-ink-muted">Build your profile, find relevant jobs, submit bids, message clients, and manage awarded work.</p><Link className="os-link" href="/marketplace/register">Join as a candidate →</Link></Card><Card title="For clients" meta="Hire with clarity"><p className="body text-ink-muted">Post a brief, compare applicants, discuss fit, approve a candidate, and manage delivery.</p><Link className="os-link" href="/marketplace/register">Join as a client →</Link></Card></section>
  </main>;
}
