/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: src/theme/openseat.theme.ts
 * Command: astryx theme build src/theme/openseat.theme.ts --out src/theme/theme.css
 * CLI: @astryxdesign/cli@0.6.2
 * Core: @astryxdesign/core@0.6.2
 */

/// <reference path="./openseat.variants.d.ts" />
import type { DefinedTheme } from "@astryxdesign/core/theme";
export /**
 *
 */
declare const openseatTheme: DefinedTheme;
