/**
 * @generated by `astryx theme build` — do not edit manually.
 * Source: lib/theme.ts
 * Command: astryx theme build lib/theme.ts --out theme/theme.css
 * CLI: @astryxdesign/cli@0.6.2
 * Core: @astryxdesign/core@0.6.2
 */

/// <reference path="./openseat.variants.d.ts" />
import type { DefinedTheme } from '@astryxdesign/core/theme';
export declare const openseatTheme: DefinedTheme;
